services:
  app:
    image: ${DOCKER_IMAGE:-secret-garden-site}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secret-garden-site
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8089:80"
    depends_on:
      - database

  database:
    image: postgres:17
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=secret-garden
      - POSTGRES_USER=example.com
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./system/service/database:/docker-entrypoint-initdb.d

volumes:
  db_data: